image: ruby:latest

stages:
 - test

variables:
  BUNDLE_PATH: 'vendor/bundle'

before_script:
  - gem install bundler
  - gem install sinatra
  - bundle install

test:
  stage: test
  script:
    - ruby -Isrc:test test/test_functions.rb